# muss man hier definieren, sonst klappt das nicht für beide includes
stages:
  - deploy_test
  - deploy_prod

include:
  # use template for gitlab pipeline to deploy to shinyapps.io
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "deploy-to-shinyapps.yml"
  # use template for gitlab pipeline to push main to github 
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "publish-main-to-github.yml"
